<a href="https://colab.research.google.com/github/harishmuh/Python-for-Data-Science-Analysis/blob/main/Folium_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# **Introduction to Folium**
---
We'll learn how to create maps for various purposes. To do this, we'll part ways with Matplotlib and work with another Python visualization library, Folium. What's interesting about Folium is that it was developed solely for the purpose of visualizing geospatial data.

While other libraries are available for visualizing geospatial data, such as plotly, they may have limitations on the number of API calls that can be made within a given time period. Folium, on the other hand, is completely free.

In [27]:
# importing libraries

# data manipulation
import numpy as np
import pandas as pd

# visualization
import folium

# Others
import requests
import json

## **1. What is Folium?**

Folium is a powerful Python library that helps you create various types of Leaflet maps. The interactive nature of Folium's output makes it particularly useful for building dashboards.

From the official Folium documentation page:

> Folium harnesses the data processing power of the Python ecosystem and the mapping power of the Leaflet.js library. Manipulate your data in Python, then visualize it on a Leaflet map using Folium.

> Folium makes it easy to visualize data manipulated in Python on an interactive Leaflet map. It allows data binding to the map for choropleth visualizations as well as passing Vincent/Vega visualizations as markers on the map.

> The library has a number of built-in tilesets from OpenStreetMap, Mapbox, and Cartodb, and supports custom tilesets with a Mapbox or Cloudmade API key. Folium supports both GeoJSON and TopoJSON overlays, as well as data binding to these overlays to create choropleth maps with color-brewer color schemes.

## **2. Generating Maps**

Creating a world map is very easy in Folium. We simply create a Folium Map object and then display it. What's great about Folium maps is that they're interactive, allowing us to zoom in to any area of interest, even at the initial zoom level.

In [28]:
# define the world_map
world_map = folium.Map()

# display world map
world_map

Try zooming in and out on the map provided above.

We can customize the default definition of this world map by specifying the center of our map and the initial zoom level.

All locations on the map are defined by their respective Latitude and Longitude values. So, we can create a map and include the center Latitude and Longitude values **[0, 0]**.

For a specified center, we can also specify the initial zoom level to that location when the map is rendered. **The higher the zoom level, the more the map zooms to its center.**

Let's create a map centered around Jakarta and play around with the zoom level to see how it affects the rendered map.

In [29]:
# Display a map of Jakarta centered on Monas
lat_monas = -6.175392
long_monas = 106.827153

jakarta_map = folium.Map([lat_monas, long_monas], zoom_start=12)
jakarta_map

## **2. Map Style**

Another cool feature of Folium is that we can generate different map styles.

### `Cartodb dark_matter Maps`

This is a black and white map with high contrast. It's suitable for data integration and exploring the meandering rivers and coastal zones.

Let's create a Cartodb dark_matter map of Surabaya with a zoom level of 12.

In [30]:
# Create a map of Surabaya
surabaya_map = folium.Map([-7.290704510409528, 112.73623511924048], zoom_start=12, tiles='Cartodb dark_matter')
surabaya_map

# location: [latitude, longitude]
# zoom_start: Initial display size
# tiles: Map style (by default, open stream map)

### `Cartodb positron Maps`

CartoDB Positron maps are designed with a light and minimalist aesthetic. They have a white or light-colored background and feature simple, clean lines for map elements. These maps are known for their modern and visually appealing design.

Let's create a Cartodb Positron Bandung map with a zoom level of 12.

In [31]:
bandung_map = folium.Map([-6.921687677732648, 107.61605423823936], zoom_start=12, tiles='Cartodb positron')
bandung_map

## **3. Maps with Markers**

We can add markers to a map. We can add these markers to our map by calling `folium.Marker()` and saving the point's location.

In [32]:
jakarta_map = folium.Map([lat_monas, long_monas], zoom_start=12)

# create a Monas marker
monas_pin = folium.Marker(
  location=[-6.175173679016957, 106.827148217066],
  tooltip='National Monument', # label when hovered
  popup='Monas is a 132-meter-high memorial monument', # label when clicked
  icon=folium.Icon(
  icon='building', # icon to display
  prefix='fa', # prefix='fa' is used when using icons from fontawesome
  color='red' # color
  )
)

# create a Halim Airport marker
halim_pin = folium.Marker(
  location=[-6.265071274791165, 106.88555279590285],
  tooltip='Halim Airport', # label when hovered
  popup='Main civil airport in Jakarta', # label when clicked
  icon=folium.Icon(
  icon='plane', # icon to display
  prefix='fa', # prefix='fa' is used if using icons from fontawesome
  color='orange' # color
  )
)

# create a circle marker
pik_area = folium.CircleMarker( # when zoomed, the size remains the same; it doesn't increase or decrease. The size is maintained in pixels
  location=[-6.1089382715126055, 106.73995330939384],
  tooltip='Pantai Indah Kapuk',
  popup='Tidal Flood Prone Area',
  radius=100, # radius in units pixel
  color='red'
)

# create a circle marker
ancol_area = folium.Circle( # zoom in or out
  location=[-6.117928361275429, 106.85017449019828],
  tooltip='Ancol Area',
  popup='Tourist area in North Jakarta',
  radius=1000, # radius in meters
  color='green'
)

ancol_area.add_to(jakarta_map)
pik_area.add_to(jakarta_map)
halim_pin.add_to(jakarta_map)
monas_pin.add_to(jakarta_map)
jakarta_map

# color options
# 'red', 'blue', 'green', 'purple', 'orange', 'darkred', 'lightred', 'beige', 'darkblue', 'darkgreen', 'cadetblue'
# 'darkpurple', 'white', 'pink', 'lightblue', 'lightgreen', 'gray', 'black', 'lightgray'

Next, we'll try creating markers with other data. Let's download and import the police department incident data using the pandas `read_csv()` method. Download the dataset and save it in a pandas dataframe:

In [33]:
df_incidents = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Police_Department_Incidents_-_Previous_Year__2016_.csv')
df_incidents.head()

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
0,120058272,WEAPON LAWS,POSS OF PROHIBITED WEAPON,Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212120
1,120058272,WEAPON LAWS,"FIREARM, LOADED, IN VEHICLE, POSSESSION OR USE",Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212168
2,141059263,WARRANTS,WARRANT ARREST,Monday,04/25/2016 12:00:00 AM,14:59,BAYVIEW,"ARREST, BOOKED",KEITH ST / SHAFTER AV,-122.388856,37.729981,"(37.7299809672996, -122.388856204292)",14105926363010
3,160013662,NON-CRIMINAL,LOST PROPERTY,Tuesday,01/05/2016 12:00:00 AM,23:50,TENDERLOIN,NONE,JONES ST / OFARRELL ST,-122.412971,37.785788,"(37.7857883766888, -122.412970537591)",16001366271000
4,160002740,NON-CRIMINAL,LOST PROPERTY,Friday,01/01/2016 12:00:00 AM,00:30,MISSION,NONE,16TH ST / MISSION ST,-122.419672,37.765050,"(37.7650501214668, -122.419671780296)",16000274071000

Each row consists of 13 features:
> 1. **IncidntNum**: Incident Number
> 2. **Category**: Category of crime or incident
> 3. **Descript**: Description of the crime or incident
> 4. **DayOfWeek**: The day of the week on which the incident occurred
> 5. **Date**: The Date on which the incident occurred
> 6. **Time**: The time of day on which the incident occurred
> 7. **PdDistrict**: The police department district
> 8. **Resolution**: The resolution of the crime in terms of whether the perpetrator was arrested or not
> 9. **Address**: The closest address to where the incident took place
> 10. **X**: The longitude value of the crime location
> 11. **Y**: The latitude value of the crime location
> 12. **Location**: A tuple of the latitude and the longitude values
> 13. **PdId**: The police department ID

Let's find out how many entries there are in our dataset.

In [34]:
df_incidents.shape

(150500, 13)

So the dataframe consists of 150,500 crimes that occurred in 2016. To reduce computational costs, let's work on the first 100 incidents in this data set.

In [35]:
df_incidents = df_incidents.head(100)

Let's check that our dataframe now consists of only 100 crimes.

In [36]:
df_incidents.shape

(100, 13)

Now that we've narrowed down the data a bit, let's visualize where these crimes occurred in San Francisco. We'll use the default style and initialize the zoom level to 12.

In [37]:
# latitude and longitude San Francisco
latitude = 37.77
longitude = -122.42

In [38]:
sanfran_map = folium.Map([latitude, longitude], zoom_start=12)
sanfran_map

Now let's put the crime scene on the map. The way to do this in Folium is to create a feature group with its own features and styles and add it to the `sanfran_map`.

In [39]:
# Create a Feature Group named incidents
incidents = folium.map.FeatureGroup()

for lat, long in list(zip(df_incidents['Y'], df_incidents['X'])):
  incidents.add_child(
    folium.vector_layers.CircleMarker(
      [lat, long],
      radius=5, # circle size
      color='yellow', # circle color
      fill=True, # fill=True means the marker will be filled with color
      fill_color='blue', # blue fill color
      fill_opacity=0.6 # opacity 60%
    )
  )

# Add Incident Group to the sanfran_map map
sanfran_map.add_child(incidents)

# Display the map
sanfran_map

We can also add some pop-up text that will appear when we hover over the markers. Let's make each marker display the crime category when hovered over.

In [40]:
# Create a Feature Group named incidents
incidents = folium.map.FeatureGroup()

for lat, long in list(zip(df_incidents['Y'], df_incidents['X'])):
  incidents.add_child(
    folium.vector_layers.CircleMarker(
        [lat, long],
        radius=5, # circle size
        color='yellow', # circle color
        fill=True, # fill=True means the marker will be filled with color
        fill_color='blue', # blue fill color
        fill_opacity=0.6 # opacity 60%
    )
  )

# Add a pop-up containing the crime type
for lat, long, label in list(zip(df_incidents['Y'], df_incidents['X'], df_incidents['Category'])):
  folium.Marker(
    [lat, long],
    popup=label
  ).add_to(sanfran_map)

# Add Group Incidents to the sanfran_map map
sanfran_map.add_child(incidents)

# Display the map
sanfran_map

Now we can see the crime category that occurred at each marker.

If we feel the map is too crowded with all these markers, there are two solutions. The simpler solution is to remove these location markers and simply add text to the circle marker itself as follows:

In [41]:
sanfran_map = folium.Map([37.77, -122.42], zoom_start=12)

# Create a Feature Group named incidents
incidents = folium.map.FeatureGroup()

for lat, long, label in list(zip(df_incidents['Y'], df_incidents['X'], df_incidents['Category'])):
  incidents.add_child(
    folium.vector_layers.CircleMarker(
      [lat, long],
      radius=5, # circle size
      color='yellow', # circle color
      fill=True, # fill=True means the marker will be filled with color
      fill_color='blue', # blue fill color
      fill_opacity=0.6, # opacity 60%
      popup=label
    )
  )

# Add Incident Group to the map sanfran_map
sanfran_map.add_child(incidents)

# show map
sanfran_map

Another viable solution is to group the markers into distinct clusters. Each cluster is then represented by the number of crimes in each neighborhood. These clusters can be thought of as pockets of San Francisco that we can then analyze separately.

To implement this, we start by initializing a `MarkerCluster` object and adding all the data points in the dataframe to this object.

In [42]:
from folium import plugins

# create map
sanfran_map = folium.Map([37.77, -122.42], zoom_start=12)

# initiate MarkerCluster
incidents = plugins.MarkerCluster().add_to(sanfran_map)

# add marker to MarkerCluster
for lat, long, label in list(zip(df_incidents['Y'], df_incidents['X'], df_incidents['Category'])):
  folium.Marker(
  [lat, long],
  popup=label,
  icon=None
  ).add_to(incidents)

# show
sanfran_map

Notice how when you zoom out completely, all the markers are combined into a single cluster, the *global cluster*, with 100 markers or crimes, which is the total number of crimes in our dataframe. As you zoom in, the *global cluster* begins to break down into smaller clusters. Zooming in all the way will yield individual markers.

## **4. Choropleth Maps**

A `Choropleth` map is a thematic map in which areas are shaded or patterned proportionally to the measurement of a statistical variable displayed on the map, such as population density or per capita income. `Choropleth` maps provide an easy way to visualize how a measurement varies across a geographic area, or show the degree of variability within a region. Below is a `Choropleth` map of the United States that depicts population per square mile by state.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/Module%205/images/2000_census_population_density_map_by_state.png" width="600">

Now we will create a `Choropleth` that depicts population movement in the city of Jakarta.

First, we read the file `pendatang_DKI_Maret_2020.csv` into the *pandas* dataframe.

In [43]:
# Loading dataset
pendatang_DKI_Maret_2020_url = 'https://raw.githubusercontent.com/harishmuh/Python-for-Data-Science-Analysis/refs/heads/main/datasets/pendatang_DKI_Maret_2020.csv'
df = pd.read_csv(pendatang_DKI_Maret_2020_url)
df.head()

,tahun,bulan,kota_kabupaten,kecamatan,kelurahan,jenis_kelamin,jumlah
0,2020,3,ADM. KEPULAUAN SERIBU,KEPULAUAN SERIBU UTARA,PULAU PANGGANG,Laki-Laki,0.0
1,2020,3,ADM. KEPULAUAN SERIBU,KEPULAUAN SERIBU UTARA,PULAU KELAPA,Laki-Laki,2.0
2,2020,3,ADM. KEPULAUAN SERIBU,KEPULAUAN SERIBU UTARA,PULAU HARAPAN,Laki-Laki,1.0
3,2020,3,ADM. KEPULAUAN SERIBU,KEPULAUAN SERIBU SELATAN,PULAU UNTUNG JAWA,Laki-Laki,3.0
4,2020,3,ADM. KEPULAUAN SERIBU,KEPULAUAN SERIBU SELATAN,PULAU TIDUNG,Laki-Laki,3.0

Next we need to display the number of immigrants based on sub-district.

In [44]:
df = df.groupby('kelurahan')[['jumlah']].sum().reset_index()
df.head()

     kelurahan  jumlah
0        ANCOL    17.0
1        ANGKE    22.0
2  BALEKAMBANG    30.0
3  BALI MESTER     4.0
4   BAMBU APUS    26.0

In [45]:
df[df['jumlah']==df['jumlah'].min()]

          kelurahan  jumlah
97   KARET SEMANGGI     0.0
214      RAWA BARAT     0.0

In order to create a Choropleth map, we need a GeoJSON file that defines the area/boundaries of a city, province, or country of interest. In this case, since we're trying to create a map of Jakarta, we need a GeoJSON that defines all the urban villages within the city. For convenience, we've provided the file [`jakarta_by_kelurahan_geo.geojson`](https://github.com/harishmuh/Python-for-Data-Science-Analysis/blob/main/datasets/jakarta_by_kelurahan_geo.geojson). Let's name it jakarta_geojson

In [ ]:
# If you manage to download the json file, you can uncomment the code below
# jakarta_geojson = r'jakarta_by_kelurahan_geo.geojson'
# pd.read_json(jakarta_geojson).loc[0, 'features']['properties']['name']

In [47]:
# Obtaining json file from github
import requests
url = 'https://raw.githubusercontent.com/harishmuh/Python-for-Data-Science-Analysis/main/datasets/jakarta_by_kelurahan_geo.geojson'
response = requests.get(url)
jakarta_geojson = response.json()

# Access the name of the first feature directly
print(jakarta_geojson['features'][0]['properties']['name'])

ANGKE

And now, to create a `Choropleth` map, we will use the *choropleth* method with the following main parameters:

1. `geo_data`, which is the GeoJSON file.
2. `data`, which is the dataframe containing the data.
3. `columns`, which represents the columns in the dataframe that will be used to create the `Choropleth` map.
4. `key_on`, which is the key or variable in the GeoJSON file that contains the desired variable name. To determine this, we need to open the GeoJSON file using any text editor and note the name of the key or variable containing the village name, since the village is the variable we are interested in. In this case, **name** is the key in the GeoJSON file that contains the village name. Note that this key is case-sensitive, so we must pass it exactly as it appears in the GeoJSON file.

In [48]:
df

             kelurahan  jumlah
0                ANCOL    17.0
1                ANGKE    22.0
2          BALEKAMBANG    30.0
3          BALI MESTER     4.0
4           BAMBU APUS    26.0
..                 ...     ...
262  UTAN KAYU SELATAN    30.0
263    UTAN KAYU UTARA    25.0
264       UTAN PANJANG    13.0
265            WARAKAS    22.0
266      WIJAYA KUSUMA    31.0

[267 rows x 2 columns]

In [49]:
# Create a map of Jakarta
jakarta_map = folium.Map(
[-6.2, 106.816666],
zoom_start=11
)

chor_kelurahan = folium.Choropleth(
  geo_data=jakarta_geojson, # geojson file
  data=df, # pandas dataframe
  columns=['kelurahan', 'jumlah'], # dataframe columns used
  key_on='feature.properties.name' # Indexing sub-district or 'kelurahan' names in the JSON file (in 'name')
)

chor_kelurahan.add_to(jakarta_map)
jakarta_map

According to the legend on the Choroplet map, the darker the color of a village and the closer it is to dark blue, the higher the rate of population migration. Therefore, population migration occurs around the Jakarta city border.

Note that some data is missing from the map. This may be because the village names in the geojson file and the dataframe are different. Therefore, we need to adjust the names first.

In [50]:
df[df['kelurahan'].str.contains('TMII')]

Empty DataFrame
Columns: [kelurahan, jumlah]
Index: []

In [51]:
df['kelurahan'] = df['kelurahan'].str.replace('WIJAYA KUSUMA', 'WIJAYA KESUMA')
df['kelurahan'] = df['kelurahan'].str.replace('JATIPULO', 'JATI PULO')
df['kelurahan'] = df['kelurahan'].str.replace('SETIA BUDI', 'SETIABUDI')
df['kelurahan'] = df['kelurahan'].str.replace('PALMERIAM', 'PAL MERIAM')
df['kelurahan'] = df['kelurahan'].str.replace('PULO GADUNG', 'PULOGADUNG')
df['kelurahan'] = df['kelurahan'].str.replace('HALIM PERDANA KUSUMAH', 'HALIM PERDANA KUSUMA')
df['kelurahan'] = df['kelurahan'].str.replace('PINANGRANTI', 'PINANG RANTI')
df['kelurahan'] = df['kelurahan'].str.replace('KRAMATJATI', 'KRAMAT JATI')
df['kelurahan'] = df['kelurahan'].str.replace('TENGAH', 'KAMPUNG TENGAH')
df['kelurahan'] = df['kelurahan'].str.replace('BALEKAMBANG', 'BALE KAMBANG')
df['kelurahan'] = df['kelurahan'].str.replace('JATI PADANG', 'JATIPADANG')
df['kelurahan'] = df['kelurahan'].str.replace('PONDOK RANGGON', 'PONDOK RANGON')

In [52]:
df.loc[267, 'kelurahan']='TMII'
df.loc[267, 'jumlah']= 0
df

           kelurahan  jumlah
0              ANCOL    17.0
1              ANGKE    22.0
2       BALE KAMBANG    30.0
3        BALI MESTER     4.0
4         BAMBU APUS    26.0
..               ...     ...
263  UTAN KAYU UTARA    25.0
264     UTAN PANJANG    13.0
265          WARAKAS    22.0
266    WIJAYA KESUMA    31.0
267             TMII     0.0

[268 rows x 2 columns]

After we fix the data, we will try to display it again while changing the colors and legend of the map.

In [54]:
range_quantile = df['jumlah'].quantile([0, 0.25, 0.5, 0.75, 1])

In [55]:
# Create a map of Jakarta
jakarta_map = folium.Map(
  [-6.2, 106.816666],
  zoom_start=11
)

chor_kelurahan = folium.Choropleth(
  geo_data=jakarta_geojson, # geojson file
  data=df, # pandas dataframe
  columns=['kelurahan', 'jumlah'], # dataframe columns used
  key_on='feature.properties.name', # indexing kelurahan names in the json file (in 'name')
  fill_color='YlOrRd', # change the color
  legend_name='Number of Newcomers', # add the name of the legend
  fill_opacity=0.5, # adjust the transparency
  bins=range_quantile
)

chor_kelurahan.add_to(jakarta_map)
jakarta_map