<a href="https://colab.research.google.com/github/harishmuh/Python-for-Data-Science-Analysis/blob/main/Intro_to_Plotly.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# **Introduction to Plotly**
---

Plotly is an interactive, open-source plotting library that supports over 40 unique chart types. Plotly is available in Python and JavaScript.

Plotly Python is an extension of the Plotly JavaScript Library and covers a wide range of chart types, including statistical, financial, map, scientific, and three-dimensional data. Web-based visualizations created using Plotly Python can be displayed in Jupiter Notebook, saved to HTML files, or served as part of a Python web application using dash.

In [21]:
# importing library

# data manipulation
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

# plotly
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# display
import warnings
warnings.filterwarnings('ignore')

In [2]:
# read dataset
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vS64B8ybc9Ud29ek8-bIYWOWV3HwqMJBd_Luy9ObflPevhUkbaJJlRalxwtlvSkHgqSlLzGrqfSC7IP/pub?gid=111658955&single=true&output=csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## **1. Barplot**
A bar plot or bar chart is a type of plot represented by bars, where the length of the bar represents the size of a feature or variable.

First, we will create a dataframe that displays the number of passengers for each class.

In [3]:
df_class= df.groupby('Pclass', as_index=False)[['PassengerId']].count()
df_class

   Pclass  PassengerId
0       1          216
1       2          184
2       3          491

Next we will use Plotly express and Plotly graph objects to plot a variety of different graphs.

### `Plotly Express (px)`

Plotly Express is a built-in extension of the Plotly library and is the recommended starting point for creating the most common Plotly-provided figures using simpler syntax.

In [4]:
px.bar(
    df_class,
    x='Pclass',
    y='PassengerId',
    title='Number of Passenger by class'
)

### `Plotly Graph Object (go)`

The Plotly Graph Object is a built-in feature of the Plotly library and is essential when we need a flexible, customizable visualization type.

First, we will create two dataframes displaying the number of passengers per class for each gender.

In [5]:
# df class gender male
df_class_male = df[df['Sex'] == 'male'].groupby('Pclass', as_index=False)[['PassengerId']].count()
df_class_male

   Pclass  PassengerId
0       1          122
1       2          108
2       3          347

In [6]:
# df class gender female
df_class_female = df[df['Sex'] == 'female'].groupby('Pclass', as_index=False)[['PassengerId']].count()
df_class_female

   Pclass  PassengerId
0       1           94
1       2           76
2       3          144

Next we will display each of these data in a separate subplot.

In [7]:
# Create 2 subplots in 1 figure

fig = make_subplots(
  rows=1,
  cols=2,
  subplot_titles=['Number of Female by class', 'Number of Male by class'],
  x_title = 'Number Passengers',
  y_title = 'Pclass'
)

# create female barplot
female_barplot = go.Bar(
  y=df_class_female['Pclass'],
  x=df_class_female['PassengerId'],
  hoverinfo= 'all',
  name='female',
  orientation='h')

# create female barplot
male_barplot = go.Bar(
  y=df_class_male['Pclass'],
  x=df_class_male['PassengerId'],
  hoverinfo= 'all',
  name='male',
  orientation='h')

# add female barplot to figure
fig.add_trace(female_barplot, 1, 1)
fig.add_trace(male_barplot, 1, 2)

fig

We can also display it in the same subplot in the form of a stacked bar chart.

In [8]:
# Create 2 subplots in 1 figure
fig = go.Figure()



# create female barplot
female_barplot = go.Bar(
  y=df_class_female['Pclass'],
  x=df_class_female['PassengerId'],
  hoverinfo= 'all',
  name='female',
  hovertemplate = 'Pclass= %{y:.0f}, Number Passenger= %{x:.0f}',
  orientation='h')

# create female barplot
male_barplot = go.Bar(
  y=df_class_male['Pclass'],
  x=df_class_male['PassengerId'],
  hoverinfo= 'all',
  name='male',
  hovertemplate = 'Pclass= %{y:.0f}, Number Passenger= %{x:.0f}',
  orientation='h')

# add female barplot to figure
fig.add_trace(female_barplot)
fig.add_trace(male_barplot)

# update layout
fig.update_layout(
barmode='stack',
title_text='Number of Passengers by Class',
title_x=0.5, # to move the title to the middle
xaxis_title='Number of Passengers',
yaxis_title='Pclass'
)

fig

## **2. Waterfall Plot**

A graph that can be used to view progress over a specific time period.

In [9]:
# loading waterfall dataset
df_waterfall = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTov2zIMZ2wFU4kXwjfReIquTuUf4UlTn-5xEuw8oWfKUGjkR7FN4Ey4tj45qz-L7EshgJdcPJZfczy/pub?gid=1123107098&single=true&output=csv')
df_waterfall

    hiring_year  resign_year  total_hired  total_resign  total_people  changes
0          2006            0            1             0             1        1
1          2007            0            2             0             3        2
2          2008            0            2             0             5        2
3          2009            0            7             0            12        7
4          2010            0            8             0            20        8
5          2011            0           76             0            96       76
6          2012         2012           41             1           136       40
7          2013         2013           43             3           176       40
8          2014         2014           56             6           226       50
9          2015         2015           31            13           244       18
10         2016         2016           14            12           246        2
11         2017         2017            5            19           232      -14
12         2018         2018            1            19           214      -18
13         2019         2019            0             7           207       -7
14         2020         2020            0            13           194      -13

First, we need to create an x-axis containing the year information. To show the final total of employees on the plot, we'll add the year 2021 to the x-axis.

In [12]:
x_axis = list(df_waterfall['hiring_year']) + [2021]
x_axis

[2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021]

Next, we'll create a y-axis that displays the annual employee changes. We'll also add the final employee total to the y-axis.

In [13]:
final_total=df_waterfall['changes'].sum()

In [15]:
y_axis = list(df_waterfall['changes']) + [final_total]
print(y_axis)

[1, 2, 2, 7, 8, 76, 40, 40, 50, 18, 2, -14, -18, -7, -13, np.int64(194)]

Next we can create a waterfall plot with plotly.

In [16]:
measure_changes = ['relative'] * len(df_waterfall) + ['total']
measure_changes

# There are 2 types of bars in the waterflaw plot

['relative',
 'relative',
 'relative',
 'relative',
 'relative',
 'relative',
 'relative',
 'relative',
 'relative',
 'relative',
 'relative',
 'relative',
 'relative',
 'relative',
 'relative',
 'total']

In [17]:
label_waterfall = [f'+{str(i)}' if i>0 else str(i) for i in y_axis]

In [18]:
layout_waterfall = go.Layout(
  title='Annual Employee changes from 2006-2020',
  yaxis={'title': "Number of Employees"},
  xaxis={'title': "Year"},
)

fig = go.Figure(layout=layout_waterfall)

# Create a waterfall plot
waterfall_plot = go.Waterfall(
  x= x_axis,
  y = y_axis,
  measure=measure_changes,
  text=label_waterfall,
  textposition='outside'
)

# Add a waterplot to the figure
fig.add_trace(waterfall_plot)



fig

## **3. Treemap Plot**

Treemaps display a sense of size and color. Treemaps are typically used to display proportions across multiple groups divided by multiple variables.

In [19]:
# display the df dataset
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [22]:
# grouping data
df_treemap = df.groupby(['Survived', 'Sex', 'Pclass']).agg({'PassengerId':len, 'Fare':np.mean}).reset_index()
df_treemap

# replacing 1 to Yes and 0 to No
df_treemap['Survived'] = df_treemap['Survived'].apply(lambda x: "Yes" if x==1 else "No")
df_treemap

   Survived     Sex  Pclass  PassengerId        Fare
0        No  female       1            3  110.604167
1        No  female       2            6   18.250000
2        No  female       3           72   19.773093
3        No    male       1           77   62.894910
4        No    male       2           91   19.488965
5        No    male       3          300   12.204469
6       Yes  female       1           91  105.978159
7       Yes  female       2           70   22.288989
8       Yes  female       3           72   12.464526
9       Yes    male       1           45   74.637320
10      Yes    male       2           17   21.095100
11      Yes    male       3           47   15.579696

In [23]:
# Treemap
fig = px.treemap(
    df_treemap,
    path=['Survived','Sex','Pclass'],
    values='PassengerId',
    color='Fare',
    color_continuous_scale='YlGnBu',
    width=1000,
    height=700,
    title='Survivablity Fact of Titanic Passenger by Gender, Pclass, Fare'
)

# Displaying the graph
fig.show()

## **4. Sunburst Plot**

Similar to a treemap, a sunburst plot is used to display proportions divided by multiple variables.

In [24]:
df_sunburst = px.data.tips()
df_sunburst

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [25]:
# Display total bill based on sex, day, time

fig = px.sunburst(
    df_sunburst,
    path=['sex','day','time'],
    values='total_bill',
    color='time',
    color_discrete_map={'Lunch':'gold', 'Dinner':'darkblue', '(?)':'black'}
)

fig.show()

You can try other beautiful plots:

| Plot Types | Function | Url Link |
| -- | -- | -- |
| Sankey Plot | Funnel Analysis | https://plotly.com/python/sankey-diagram/ |
| Parallel Categories Diagram | Funnel Analysis | https://plotly.com/python/parallel-categories-diagram/ |
| Maps Related Plot | Geographic Analysis | https://plotly.com/python/maps/ |
| Statistics-related Plot | Statistical Analysis | https://plotly.com/python/statistical-charts/ |
| AI and Machine Learning-related Plot | ML Performance Visualization | https://plotly.com/python/ai-ml/ |
| Economic-related Plot | Time Series, Funnel, and Indicator Analysis | https://plotly.com/python/financial-charts/ |

Some plotly functions:

| Plot Types | Plot Types | Plot Types | Plot Types |
| -- | -- | -- | -- |
| px.area() |  px.funnel() | px.parallel_categories() | px.sunburst() |
| px.bar() | px.funnel_area() | px.pie() | px.timeline() | px.treemap() |
| px.bar_polar() | px.get_trendline_results() | px.scatter() | px.violin() |
| px.box() |px.histogram() | px.scatter_3d() | px.scatter_geo() |
| px.choropleth() | px.line() | px.scatter_mapbox() |
| px.choropleth_mapbox() | px.line_3d() | px.scatter_matrix() |
| px.density_contour() | px.line_mapbox() |  px.scatter_polar() |
| px.density_heatmap() | px.line_polar() | px.scatter_ternary() |
| px.density_mapbox() | px.line_ternary() | px.strip() |

## **5. Pie Chart**
Pie charts are one of the most popular chart formats used to present data.

In [26]:
# Create grouped survival data
df_survival = df.groupby(["Survived"]).count()["PassengerId"].reset_index()
df_survival["Survived"] = df_survival["Survived"].map(lambda x: "Yes" if x == 1 else "No")
df_survival

  Survived  PassengerId
0       No          549
1      Yes          342

In [27]:
# Create grouped gender data
df_gender = df.groupby(["Sex"]).count()["PassengerId"].reset_index()
df_gender

      Sex  PassengerId
0  female          314
1    male          577

In [28]:
# Plotly Express
fig = px.pie(df_survival,
             names = "Survived",
             values= "PassengerId",
             title = "Percentage of Passenger Survival")
fig.show()

In [29]:
# Graphic Objects Plotly (Advanced)
# Create subplot with 1 row and 2 columns
# in matplotlib, this is similar with plt.subplots(1, 2)
fig = go.Figure()

# Create first pie plot about survival data in coords (1,1)
fig.add_trace(go.Pie(labels = df_survival["Survived"],
                     values = df_survival["PassengerId"],
                     name  = "Survive?",
                     marker= {'colors': ["Red","LightSkyBlue"]}),
              )

# ==============================================================
# Lets make up our pie chart, harnessing the go shapes and texts
# ==============================================================

# 1. Add hole in the center
fig.update_traces(hole=0.7, hoverinfo="label+percent+name")

# 2. Add 5 text based on certain coordinates
fig.update_layout(
    title_text="Number of Passenger based on Survival Status",
    showlegend=False,
    annotations=[dict(text="Total Passenger", x=0.17+0.33, y=0.65, font_size=15, showarrow=False),
                 dict(text=str(df_survival["PassengerId"].sum()), x=0.190+0.31, y=0.55, font_size=40, showarrow=False),
                 dict(text="Y", x=0.481, y=0.425, font_size=15, showarrow=False),
                 dict(text="N", x=0.481+0.06, y=0.425, font_size=15, showarrow=False),
                ])

# 3. Add two additional boxes
## First Box (Blue Color)
fig.add_shape(type="rect",
    x0=0.1+0.35,
    y0=0.40,
    x1=0.2+0.27,
    y1=0.45,
    line=dict(
        color="Black",
        width=2,
    ),
    fillcolor="LightSkyBlue",
)

## Second Box (Red Color)
fig.add_shape(type="rect",
    x0=0.18+0.06+0.27,
    y0=0.40,
    x1=0.2+0.06+0.27,
    y1=0.45,
    line=dict(
        color="Black",
        width=2,
    ),
    fillcolor="Red",
)

# Show the result
fig.show()

## **6. Stacked Bar (Percentage)**

In [30]:
# Graphic Objects Plotly (Advanced Barchart)

# Create text label
top_labels = ['Strongly agree', 'Agree', 'Neutral', 'Disagree',
              'Strongly disagree']

# Define labels
colors = ['rgba(38, 24, 74, 0.8)', 'rgba(71, 58, 131, 0.8)',
          'rgba(122, 120, 168, 0.8)', 'rgba(164, 163, 204, 0.85)',
          'rgba(190, 192, 213, 1)']

# Create matrix for survey data (The sum of each vector must be 100 (Percentage))
x_data = [[21, 30, 21, 16, 12],
          [24, 31, 19, 15, 11],
          [27, 26, 23, 11, 13],
          [29, 24, 15, 18, 14]]

# Define y label axis
y_data = ['The course was effectively<br>organized',
          'The course developed my<br>abilities and skills ' +
          'for<br>the subject', 'The course developed ' +
          'my<br>ability to think critically about<br>the subject',
          'I would recommend this<br>course to a friend']

fig = go.Figure()

# Create base Barplot for each vector
for i in range(0, len(x_data[0])):
    for xd, yd in zip(x_data, y_data):
        fig.add_trace(go.Bar(
            x=[xd[i]], y=[yd],
            orientation='h',
            marker=dict(
                color=colors[i],
                line=dict(color='rgb(248, 248, 249)', width=1)
            )
        ))

# Add update layout to beautify the visualization
fig.update_layout(
    xaxis=dict(
        showgrid=False,
        showline=False,
        showticklabels=False,
        zeroline=False,
        domain=[0.15, 1]
    ),
    yaxis=dict(
        showgrid=False,
        showline=False,
        showticklabels=False,
        zeroline=False,
    ),
    barmode='stack',
    paper_bgcolor='rgb(248, 248, 255)',
    plot_bgcolor='rgb(248, 248, 255)',
    margin=dict(l=120, r=10, t=140, b=80),
    showlegend=False,
)

# Add label text
annotations = []
for yd, xd in zip(y_data, x_data):

    # labeling the y-axis
    annotations.append(dict(xref='paper', yref='y',
                            x=0.14, y=yd,
                            xanchor='right',
                            text=str(yd),
                            font=dict(family='Arial', size=14,
                                      color='rgb(67, 67, 67)'),
                            showarrow=False, align='right'))

    # labeling the first percentage of each bar (x_axis)
    annotations.append(dict(xref='x', yref='y',
                            x=xd[0] / 2, y=yd,
                            text=str(xd[0]) + '%',
                            font=dict(family='Arial', size=14,
                                      color='rgb(248, 248, 255)'),
                            showarrow=False))

    # labeling the first Likert scale (on the top)
    if yd == y_data[-1]:
        annotations.append(dict(xref='x', yref='paper',
                                x=xd[0] / 2, y=1.1,
                                text=top_labels[0],
                                font=dict(family='Arial', size=14,
                                          color='rgb(67, 67, 67)'),
                                showarrow=False))

    space = xd[0]
    for i in range(1, len(xd)):
            # labeling the rest of percentages for each bar (x_axis)
            annotations.append(dict(xref='x', yref='y',
                                    x=space + (xd[i]/2), y=yd,
                                    text=str(xd[i]) + '%',
                                    font=dict(family='Arial', size=14,
                                              color='rgb(248, 248, 255)'),
                                    showarrow=False))

            # labeling the Likert scale
            if yd == y_data[-1]:
                annotations.append(dict(xref='x', yref='paper',
                                        x=space + (xd[i]/2), y=1.1,
                                        text=top_labels[i],
                                        font=dict(family='Arial', size=14,
                                                  color='rgb(67, 67, 67)'),
                                        showarrow=False))
            space += xd[i]

fig.update_layout(annotations=annotations)

fig.show()

## **Demographic Map**

In [31]:
# Display age descriptive statistics
df["Age"].describe().to_frame()

              Age
count  714.000000
mean    29.699118
std     14.526497
min      0.420000
25%     20.125000
50%     28.000000
75%     38.000000
max     80.000000

In [32]:
# There are so many noises in the data, and 88 unique values. Its better to make age groups, so the visualization will be more tidy.

# We create age group based on the desired distances
df["age_group"] = df["Age"].map(lambda x: "0 - 10"  if 0<=x<=10 else\
                                          "11 - 20" if 11<=x<=20 else\
                                          "21 - 30" if 21<=x<=30 else\
                                          "31 - 40" if 31<=x<=40 else\
                                          "41 - 50" if 41<=x<=50 else\
                                          ">=51")

# Store the group name into a list
age_group_list = ["0 - 10", "11 - 20", "21 - 30", "31 - 40", "41 - 50", ">=51"]

# Let see the distribution
df.groupby(["age_group"])["PassengerId"].count()
# Then we create another group by using Gender
df_demographic = df.groupby(["Sex","age_group"])["PassengerId"].count().reset_index()
df_demographic = df_demographic.sort_values(["Sex","age_group"],ascending=[False,False]).reset_index(drop=True)
df_demographic

       Sex age_group  PassengerId
0     male      >=51          175
1     male   41 - 50           53
2     male   31 - 40           99
3     male   21 - 30          148
4     male   11 - 20           69
5     male    0 - 10           33
6   female      >=51           71
7   female   41 - 50           31
8   female   31 - 40           54
9   female   21 - 30           81
10  female   11 - 20           46
11  female    0 - 10           31

In [33]:

# Now lets make the demographic plot
# Demographic plot is basically a stacked bar chart, however the middle point is 0 (value)
# The strategy is: Create 2 bar charts,the first 1 must be negative, the second one positive in the same axis (y)

# 1. Separate female and female data in order to extract their passenger number by age groups
df_demographic_female = df_demographic.query("Sex!='male'").set_index(["age_group"])
df_demographic_male = df_demographic.query("Sex=='male'").set_index(["age_group"])

# 2a. Extract female passenger Id Data, then make it negative (-1), since we want to show the female color in left side
female_bins = np.array(df_demographic_female["PassengerId"].tolist())*-1

# 2b. While the male passenger is positive number
men_bins = np.array(df_demographic_male["PassengerId"].astype(int).tolist())

# 3. Store the maximum value, and the distance range in plot
max_value = df_demographic["PassengerId"].max()
jump = round(df_demographic["PassengerId"].max()/3)

# 4. Create the layout
layout = go.Layout(yaxis=go.layout.YAxis(title='Age Group',
                                         ticktext=df_demographic["age_group"].unique()
                                        ),
                   xaxis=go.layout.XAxis(
                           range   = [-max_value, max_value],
                           tickvals = [-max_value, -max_value+jump, -max_value+jump*2, 0 , max_value-jump*2, max_value-jump, max_value],
                           ticktext = [max_value,   max_value-jump, max_value-jump*2 , 0 , max_value-jump*2,  max_value-jump, max_value],
                           title='Number of Passengers'),
                   barmode='overlay',
                   bargap=0.2,
                   title="Titanic Passenger based on Age Group and Gender")

# 5. Create the figure
fig = go.Figure(layout=layout)

# 6a. Create barplot for Male
fig.add_trace(go.Bar(  x = men_bins,
                       y = age_group_list,
                       orientation='h',
                       name='Male',
                       hoverinfo='x',
                       marker=dict(color='seagreen')
                       ))

# 6b. Create barplot for Female
fig.add_trace(go.Bar(  x = female_bins,
                       y = age_group_list,
                       orientation='h',
                       name='Female',
                       # text=-1 * female_bins.astype('int'),
                       hoverinfo='x',
                       marker=dict(color='pink')
                       ))
# 7. Show the result
fig.show()